### ISSUE TITLE
The invalid url: "http://samaritan89.github.io/"

### ISSUE THREAD

**Issue by yeshiqing** [Samaritan89/samaritan89.github.com#6]
Hi，teacher Byron, I'm 世清 from FE class 3 of hunger valley.
The online blog `http://samaritan89.github.io/` ,which shows on `https://github.com/Samaritan89/FE-Tutorial/tree/master/f2e_guid`, is invalid.

But I suddenly have a question about the return value of the execution of operator `new`.

I just want to have a look at how you taught this point at that time. :yum: (Of course, it doesn't matter exactly since I can get the relevant info from other places)

**Comment by qx2io** [comment]
世清可以加一下我微信  UndefinedStyle
